### ISSUE TITLE
Where's the license?

### ISSUE THREAD

**Issue by Creative-Difficulty** [airbadge-dev/airbadge#13]

**Comment by joshnuss** [comment]
Hi @Creative-Difficulty,

I've updated the license in the repo.
See: https://github.com/airbadge-dev/airbadge/blob/main/LICENSE.md

The project is currently using a BSL License that reverts to GPL after 5 years. 
It is designed so that the project is free to use, but third parties are not allowed to resell it without permission, since I may sell add on services in the future to support development of the project.
