### ISSUE TITLE
Docs Improvement?

### ISSUE THREAD

**Issue by ondrejjcizek** [airbadge-dev/airbadge#3]
Hi @joshnuss,

I tried to get it done. I am running on Drizzle + Turso. I rewrite MySQL to SQLite.

I reached only that I can login with GitHub and then subscibed to mine created Basic Plan. But subscription is missing in data. Don't know why.

<img width="765" alt="image" src="https://github.com/joshnuss/airbadge/assets/14270194/7cb2efa6-d48f-4669-a39a-2e8f0eb8c596">

Another thing is signing out. Auth.js have {handle, signOut, signIn}. But it's not here...
/auth/signout have signout button when click it I see this.

<img width="431" alt="image" src="https://github.com/joshnuss/airbadge/assets/14270194/d68fe343-f535-4040-9412-35e1165c8fff">

Also I tried Google Provider and it's not working. I have there Error 400: redirect_uri_mismatch. In Google Console I have same callback  as for GitHub

<img width="528" alt="image" src="https://github.com/joshnuss/airbadge/assets/14270194/73762366-507f-4216-a2b1-31962fcb799e">

I read 100% but there is not too much info to get it work :(

**Comment by joshnuss** [comment]
Hi Ondrejj,

Thanks for opening an issue, I will definitely be updating docs.

If you'd like to hop on a Discord call, I'd be happy to help debug these issues.

You can try importing `{handle, signOut, signIn}` from `@auth/sveltekit`, but I think you are making a good point that it should be re-exported by `@airbadge/sveltekit`.

For Drizzle, I think there will need to be an update to the adapter. I kind of mentioned it as "coming soon" in the docs: https://docs.airbadge.dev/database#drizzle

The reason is that the Drizzle adapter for Auth.js, it hardcoding the types. So either a custom drizzle adapter will be needed, or the ability to extend the Auth.js adapter is needed.

**Comment by joshnuss** [comment]
The repo has been updated to Auth.js v5 which fixes these issues.

The drizzle adapter is not yet supported, but will come eventually.
